name: refresh-top-llms
on:
  schedule:
    - cron:  '0 2 * * *'   # 02:00 UTC dagelijks
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.x'}
      - run: pip install pandas requests
      - run: python generate.py
      - run: |
          git config user.name "bot"; git config user.email "bot@users.noreply.github.com"
          git add top-llms.json
          git commit -m "auto-update" || echo "no changes"
          git push
